global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'taste-karachi-monitor'

# Alertmanager configuration (optional - can be added later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application metrics
  - job_name: 'fastapi'
    scrape_interval: 10s
    static_configs:
      - targets: ['fastapi:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  # Streamlit application (if you add metrics)
  # - job_name: 'streamlit'
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ['streamlit:8501']
  #   metrics_path: '/metrics'
