channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.3
- pip:
  - mlflow==2.9.0
  - cloudpickle==3.1.1
  - numpy==1.26.2
  - packaging==25.0
  - psutil==7.1.2
  - pyyaml==6.0.3
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
